<?php


namespace App\Form;


use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ForwardMessageFormType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('receiver', TextType::class, [
                'label' => "To",
                'attr' => [
                  'placeholder' => "Enter username or user id",
                    'style' => 'width:25%'
                ],
                'required' => true
            ])
            ->add('subject', TextType::class, [
                'label' => 'Subject',
                'attr' => [
                    'class' => 'w-100'
                ],
                'required' => true
            ])
            ->add('message', TextareaType::class, [
                'required' => false,
                'data' => $options['data']['forwarded']
            ])
            ->add('send', SubmitType::class, [
                'attr' => [
                    'class' => 'btn'
                ]
            ]);
    }
    public function configureOptions(OptionsResolver $resolver)
    {
        parent::configureOptions($resolver); // TODO: Change the autogenerated stub
    }
}